//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tours_Travels
{
    public partial class AdminBookingReports
    {
        protected global::System.Web.UI.WebControls.Panel pnlInfo;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblInfo;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.DropDownList ddlReportType;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnGenerateReport;
        protected global::System.Web.UI.WebControls.Button btnExportPDF;
        protected global::System.Web.UI.WebControls.Button btnExportExcel;
        protected global::CrystalDecisions.Web.CrystalReportViewer CrystalReportViewer1;
    }
}
