//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tours_Travels
{
    public partial class Home
    {
        /// <summary>
        /// txtDestination control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Field type: System.Web.UI.WebControls.TextBox
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDestination;

        /// <summary>
        /// txtDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Field type: System.Web.UI.WebControls.TextBox
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDate;

        /// <summary>
        /// txtTravelers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Field type: System.Web.UI.WebControls.TextBox
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTravelers;

        /// <summary>
        /// btnHeroSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// Field type: System.Web.UI.WebControls.Button
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnHeroSearch;
    }
}
